curl -Ls https://www.espron.sk/rucne-omietky -o _snapshot/espron/html/rucne-omietky.html
curl -Ls https://www.espron.sk/zateplenie-fasady/trencin -o _snapshot/espron/html/zateplenie-fasady__trencin.html
curl -Ls https://www.espron.sk/interierovy-dizajn -o _snapshot/espron/html/interierovy-dizajn.html
curl -Ls https://www.espron.sk/zateplenie-fasady/mineralna-vlna -o _snapshot/espron/html/zateplenie-fasady__mineralna-vlna.html
curl -Ls https://www.espron.sk/zateplenie-fasady/trnava -o _snapshot/espron/html/zateplenie-fasady__trnava.html
curl -Ls https://www.espron.sk/zateplenie-fasady/svojpomocne -o _snapshot/espron/html/zateplenie-fasady__svojpomocne.html
curl -Ls https://www.espron.sk/zateplenie-fasady/faq -o _snapshot/espron/html/zateplenie-fasady__faq.html
curl -Ls https://www.espron.sk/zateplenie-fasady -o _snapshot/espron/html/zateplenie-fasady.html
curl -Ls https://www.espron.sk/tepovanie -o _snapshot/espron/html/tepovanie.html
curl -Ls https://www.espron.sk/zateplenie-fasady/kosice -o _snapshot/espron/html/zateplenie-fasady__kosice.html
curl -Ls https://www.espron.sk/zateplenie-fasady/nitra -o _snapshot/espron/html/zateplenie-fasady__nitra.html
curl -Ls https://www.espron.sk/zateplenie-fasady/polystyren-biely-sivy -o _snapshot/espron/html/zateplenie-fasady__polystyren-biely-sivy.html
curl -Ls https://www.espron.sk/kontakt -o _snapshot/espron/html/kontakt.html
curl -Ls https://www.espron.sk/sadrokartonove-prace -o _snapshot/espron/html/sadrokartonove-prace.html
curl -Ls https://www.espron.sk/zateplenie-fasady/bratislava -o _snapshot/espron/html/zateplenie-fasady__bratislava.html
curl -Ls https://www.espron.sk/o-nas -o _snapshot/espron/html/o-nas.html
curl -Ls https://www.espron.sk/cistenie-dlazby -o _snapshot/espron/html/cistenie-dlazby.html
curl -Ls https://www.espron.sk/cistenie-fasady -o _snapshot/espron/html/cistenie-fasady.html
curl -Ls https://www.espron.sk/personalny-leasing-stavbarov -o _snapshot/espron/html/personalny-leasing-stavbarov.html
curl -Ls https://www.espron.sk -o _snapshot/espron/html/home.html
